# Generated by Django 6.0 on 2026-02-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='category',
            new_name='categorie',
        ),
    ]
