# Generated by Django 6.0 on 2026-02-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_category_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='game',
            name='metacritic_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='studio_logos/'),
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.categories'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
