# Generated by Django 6.0 on 2026-02-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_categories_remove_game_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
    ]
