# Generated by Django 6.0 on 2026-02-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_categories_options_remove_game_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='metacritic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
